name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # -------- Docker Login --------
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -------- Build & Push Backend --------
      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/crud-dd-task-mean-app_backend:latest

      # -------- Build & Push Frontend --------
      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/crud-dd-task-mean-app_frontend:latest


  test:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build & Start Containers
        run: docker-compose up -d --build

      - name: Wait for services to start
        run: sleep 20

      - name: Check Running Containers
        run: docker ps

      - name: Test Backend
        run: curl --fail http://localhost:5000

      - name: Test Frontend
        run: curl --fail http://localhost:4200

      - name: Shutdown Containers
        if: always()
        run: docker-compose down
